# docs: https://github.com/moulco/moul/tree/master/docs#example-moultoml
base = "https://kaylaloops.com"
ga_measurement_id = ""

[style]
theme = "system-preference"
cover = "center"
content = "left"

[profile]
name = "Kayla Loops"
bio = "makemeloops@gmail.com"

[social]
twitter = ""
github = ""
instagram = ""
facebook = ""
youtube = ""

[content]
title = "Loops"
tags = ["Crochet", "Creative"]
text = """
I am the proud owner of way too much yarn and too much time. Kayla Loops started as me just looping on crochet projects. I am unstoppable. I love creating new projects. If you'd like me to create you your own personal loops/project, send me a message and I might make it happen. I will only be creating new patterns as I don't save my random ones. I do them all by obsessing, randomly make up my own and by googling fun ideas.
"""
